# This file was generated by the {rix} R package v0.18.2 on 2026-06-19
# with following call:
# >rix(date = "2025-12-29",
#  > r_pkgs = c("languageserver",
#  > "quarto",
#  > "knitr",
#  > "rmarkdown",
#  > "pacman",
#  > "rix",
#  > "here",
#  > "data.table",
#  > "ggplot2",
#  > "fixest",
#  > "broom",
#  > "glue",
#  > "kableExtra",
#  > "bit64",
#  > "readxl",
#  > "readr",
#  > "dplyr",
#  > "lubridate",
#  > "tidyr",
#  > "R.utils",
#  > "stringr"),
#  > system_pkgs = "quarto",
#  > git_pkgs = NULL,
#  > tex_pkgs = c("amsmath",
#  > "amsfonts",
#  > "geometry",
#  > "setspace",
#  > "threeparttable",
#  > "tools",
#  > "ulem"),
#  > jl_conf = list(jl_version = "1.11",
#  > jl_pkgs = c("BenchmarkTools",
#  > "CSV",
#  > "DataFrames",
#  > "Distributions",
#  > "ForwardDiff",
#  >      "Interpolations",
#  > "LinearAlgebra",
#  > "NLsolve",
#  > "Optim",
#  > "Plots",
#  > "PrettyTables",
#  > "QuantEcon",
#  > "Random",
#  > "Roots",
#  > "Statistics",
#  > "StatsBase",
#  > "JuMP",
#  > "Ipopt")),
#  > ide = "none",
#  > project_path = path_default_nix,
#  > overwrite = TRUE,
#  > print = TRUE,
#  > shell_hook = "\n    # Make R.nvim's vendored nvimcom package available without writing\n      # to a global R library. rix's .Rprofile strips R_LIBS_USER but\n      # leaves R_LIBS_SITE alone.\n        export R_LIBS_SITE=\"$PWD/.Rlib:$R_LIBS_SITE\"\n        mkdir -p \"$PWD/.Rlib\"\n        rm -f ~/.local/share/nvim/lazy/R.nvim/nvimcom/src/apps/rnvimserver\n        R CMD INSTALL --library=\"$PWD/.Rlib\" ~/.local/share/nvim/lazy/R.nvim/nvimcom\n    ",
#  >      r_ver = "4.5.2")
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2025-12-29.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      bit64
      broom
      data_table
      dplyr
      fixest
      ggplot2
      glue
      here
      kableExtra
      knitr
      languageserver
      lubridate
      pacman
      quarto
      R_utils
      readr
      readxl
      rix
      rmarkdown
      stringr
      tidyr;
  };
  
  tex = (pkgs.texlive.combine {
    inherit (pkgs.texlive) 
      scheme-small
      amsfonts
      amsmath
      geometry
      setspace
      threeparttable
      tools
      ulem;
  });
  
  jlconf = pkgs.julia_111.withPackages [ 
      "BenchmarkTools"
      "CSV"
      "DataFrames"
      "Distributions"
      "ForwardDiff"
      "Interpolations"
      "Ipopt"
      "JuMP"
      "LinearAlgebra"
      "NLsolve"
      "Optim"
      "Plots"
      "PrettyTables"
      "QuantEcon"
      "Random"
      "Roots"
      "Statistics"
      "StatsBase"
  ];
  
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      glibcLocales
      nix
      quarto
      R
      which
      pandoc;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.stdenv.hostPlatform.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    buildInputs = [ rpkgs tex jlconf system_packages ];
    shellHook = ''
    
    # Make R.nvim's vendored nvimcom package available without writing
      # to a global R library. rix's .Rprofile strips R_LIBS_USER but
      # leaves R_LIBS_SITE alone.
        export R_LIBS_SITE="$PWD/.Rlib:$R_LIBS_SITE"
        mkdir -p "$PWD/.Rlib"
        rm -f ~/.local/share/nvim/lazy/R.nvim/nvimcom/src/apps/rnvimserver
        R CMD INSTALL --library="$PWD/.Rlib" ~/.local/share/nvim/lazy/R.nvim/nvimcom
    
  '';
  }; 
in
  {
    inherit pkgs shell;
  }
